/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff */
        get: operations["diff_api_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_api_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_api_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa */
        get: operations["spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommentOut
         * @description One message in a thread.
         */
        CommentOut: {
            /** Id */
            id: number;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
        };
        /**
         * DiffFile
         * @description A single file's section of a diff.
         */
        DiffFile: {
            /** Path */
            path: string;
            /** Old Path */
            old_path: string;
            /** Hunks */
            hunks: components["schemas"]["Hunk"][];
        };
        /**
         * DiffResponse
         * @description The structured diff for one scope.
         */
        DiffResponse: {
            /** Scope */
            scope: string;
            /** Files */
            files: components["schemas"]["DiffFile"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hunk
         * @description A contiguous block of changes with its ``@@`` ranges and rows.
         */
        Hunk: {
            /** Old Start */
            old_start: number;
            /** Old Count */
            old_count: number;
            /** New Start */
            new_start: number;
            /** New Count */
            new_count: number;
            /** Header */
            header: string;
            /** Rows */
            rows: components["schemas"]["Row"][];
        };
        /**
         * Row
         * @description One rendered diff line. ``old_line_no`` is null on adds, ``new_line_no`` on deletes.
         */
        Row: {
            /** Old Line No */
            old_line_no: number | null;
            /** New Line No */
            new_line_no: number | null;
            type: components["schemas"]["RowType"];
            /** Content */
            content: string;
        };
        /**
         * RowType
         * @description The role a single diff row plays within a hunk.
         * @enum {string}
         */
        RowType: "context" | "add" | "delete";
        /**
         * Side
         * @description Which side of the diff a thread anchors to (deletes have only ``OLD``).
         * @enum {string}
         */
        Side: "old" | "new";
        /**
         * ThreadCreate
         * @description Request body for creating a single-line note.
         */
        ThreadCreate: {
            /** File Path */
            file_path: string;
            side: components["schemas"]["Side"];
            /** Line */
            line: number;
            /** Body */
            body: string;
        };
        /**
         * ThreadOut
         * @description A note anchored to a single diff line, with its comments nested.
         */
        ThreadOut: {
            /** Id */
            id: number;
            /** Scope */
            scope: string;
            /** File Path */
            file_path: string;
            side: components["schemas"]["Side"];
            /** Line */
            line: number;
            /** Created At */
            created_at: string;
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
        };
        /**
         * ThreadsResponse
         * @description The review threads for one scope.
         */
        ThreadsResponse: {
            /** Scope */
            scope: string;
            /** Threads */
            threads: components["schemas"]["ThreadOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    diff_api_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
        };
    };
    list_threads_api_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadsResponse"];
                };
            };
        };
    };
    create_thread_api_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
